sudo: required
services:
  - docker

before_install:
  - docker build -t langstonmenezes/docker-react -f  Dockerfile.dev . 

script:
  - docker run langstonmenezes/docker-react npm run test -- --coverage